package br.com.ricardolonga.drools
 
import br.com.ricardolonga.drools.domain.Pessoa;
import br.com.ricardolonga.drools.domain.Pessoa.Sexo;
import br.com.ricardolonga.drools.domain.Pessoa.EstadoCivil;
 
dialect "java" 
  
rule "Se você for bonito" no-loop ruleflow-group "voce-eh-bonito"
    when
        $p : Pessoa( sexo == Sexo.MASCULINO, bonito == true )
    then
        System.out.println($p.getNome() + " e bonito.");
end
  
rule "Se você for feio" no-loop ruleflow-group "voce-eh-bonito"
    when
        $p : Pessoa( sexo == Sexo.MASCULINO, bonito == false )
    then
        System.out.println($p.getNome() + " e feio.");
end
