package br.com.ricardolonga.drools
 
import br.com.ricardolonga.drools.domain.Pessoa;
import br.com.ricardolonga.drools.domain.Pessoa.Sexo;
import br.com.ricardolonga.drools.domain.Pessoa.EstadoCivil;
 
dialect "java" 
 
rule "Se tem dinheiro" no-loop ruleflow-group "voce-tem-dinheiro"
    when
        $p : Pessoa( sexo == Sexo.MASCULINO, rico == true )
    then
        System.out.println($p.getNome() + " e rico.");
end
 
rule "Se é pobre" no-loop ruleflow-group "voce-tem-dinheiro"
    when
        $p : Pessoa( sexo == Sexo.MASCULINO, rico == false )
    then
        System.out.println($p.getNome() + " e pobre.");
end
